# Generated by Django 3.2.8 on 2022-08-26 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Clase', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_first_name', models.CharField(max_length=100, null=True)),
                ('arabic_last_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('class_field', models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.clase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsPrimary2',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arabic', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('arabic_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('islamic', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('islamic_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('math', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('math_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('science', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('science_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('civil', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('civil_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('hist_geo', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('hist_geo_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('french', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('french_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectsPrimary1',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('arabic', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('arabic_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('islamic', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('islamic_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('math', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('math_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('science', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('science_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('civil', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('civil_score', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
