# Generated by Django 3.2.8 on 2022-08-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_field',
            field=models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.clase'),
        ),
    ]
